[package]
name = "binance_orderbooks"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
arrayvec = { version = "0.7", features = ["serde"] }
